WestpacGEL/GEL

.circleci/config.yml
components/grid/tests/unit/grid.spec.js
package.json
yarn.lock

Signed-off-by: Dominik Wilkowski <Hi@Dominik-Wilkowski.com>

maybe with branch?

---

README.md

Signed-off-by: Dominik Wilkowski <Hi@Dominik-Wilkowski.com>

added shield

---

components/hooks/src/index.js
components/media-queries/examples/10-value-arrays.js
components/media-queries/src/index.js

also added a media-query example

fix export path for hooks/media-queries;

---

brands/BOM/tokens/index.js
brands/BSA/tokens/index.js
brands/BTFG/tokens/index.js
brands/STG/tokens/index.js
brands/WBC/tokens/index.js
brands/WBG/tokens/index.js
components/grid/docs.mdx
components/tabcordion/src/styled.js

- populate missing color tokens
- remove hard-coded color values from tabcordion

Brand colors

---

README.md
doczrc.js

Signed-off-by: Dominik Wilkowski <Hi@Dominik-Wilkowski.com>

added docs stufffffff

---

helpers/cli.js

_ref_ https://github.com/WestpacGEL/GEL/issues/80#issuecomment-517086548

fix(cli): ensure we have correct values to replace .component-template with

---

brands/BOM/tokens/index.js
brands/BSA/tokens/index.js
brands/BTFG/tokens/index.js
brands/STG/tokens/index.js
brands/WBC/tokens/index.js
brands/WBG/tokens/index.js
components/alert/src/Alert.js

and div and span to also inherit text color

Fix/alert: correct alert background color tokens

---

components/badge/docs.mdx
components/badge/examples/00-appearance.js
components/badge/examples/10-links.js
components/badge/examples/20-buttons.js
components/badge/src/Badge.js

This PR...
1. Changes prop value `appearance="info"` to `appearance="information"` for consistency as per Label, Button etc
1. Simplifies token consumption

Badge tweak

---

components/accessibility-helpers/docs.mdx
components/accessibility-helpers/examples/00-SrOnly.js
components/accessibility-helpers/examples/10-SrSkipLink.js
components/accessibility-helpers/src/SrOnly.js
components/accessibility-helpers/src/SrSkipLink.js
components/accessibility-helpers/src/index.js

Bringing over this simple accessibility helper across from GUI2.0
Ref https://github.com/WestpacGEL/GEL/issues/103

SrSkipLink

---

components/core/src/Core.js
components/core/src/index.js
components/core/src/utils.js
components/grid/src/Cell.js
components/grid/src/Container.js
components/grid/src/Grid.js

abstracting paint function into its own hook

feat(core): add useMediaQuery

---

components/grid/src/Cell.js

Didnt call useMediaQuery properly and broke the grid

fix(grid): fix mediaQuery call

---

components/button-group/docs.mdx
components/button-group/src/ButtonGroup.js
components/button-group/src/ButtonGroupButton.js

@simonswiss Is this a better approach to child styling, rather than overriding child button styling via `:first-child`/`:last-child` CSS selectors?

ButtonGroup POC

---

components/button-group/docs.mdx
components/button-group/examples/00-appearance.js
components/button-group/src/ButtonGroup.js
components/button/docs.mdx
components/button/examples/00-appearance.js
components/button/examples/10-button-tags.js
components/button/examples/20-sizes.js
components/button/examples/30-block.js
components/button/examples/40-active-state.js
components/button/examples/50-disabled-state.js
components/button/examples/60-icons.js
components/button/examples/70-options.js
components/button/src/Button.js

Neutral is not required as an appearance option in Button

Remove neutral option from Button and ButtonGroup

---

components/button/examples/10-button-tags.js
components/button/src/Button.js

Ensures `<button />` elements always get a button type (unless something else is set)

Fix Button

---

components/progress-rope/examples/10-group.js
components/progress-rope/examples/20-overrides.js
components/progress-rope/package.json
components/progress-rope/src/Group.js
components/progress-rope/src/Item.js
components/progress-rope/src/ProgressRope.js
components/progress-rope/src/_utils.js
components/progress-rope/src/overrides/group.js
components/progress-rope/src/overrides/groupButton.js
components/progress-rope/src/overrides/groupItems.js
components/progress-rope/src/overrides/item.js
components/progress-rope/src/overrides/itemButton.js
components/progress-rope/src/overrides/progressRope.js

- Move rope to LHS
- Increase gap under last group item
- Compete state styling, new circle styling, dashed line etc
- Update examples
- Fill circles using border; better HCM support
- Add aria-controls

Merge progress-rope updates into accessibility fixes branch

---

website/dynamic-blocks/props-table.js

added some design tweaks

---

website/src/components/layout/footer.js

Fix top link in footer

---

babel.config.js
website/src/components/pages/single-component/_utils.js

Also includes babel config updates

Fix related link style

---

babel.config.js
website/dynamic-blocks/intro-section.js
website/src/components/pages/single-component/blocks-hub.js

Makes the Table of content work properly

tick tick TOC

---

website/dynamic-blocks/do-and-avoid.js
website/src/components/pages/single-component/blocks-hub.js

- make do-don't layout responsive
- use LAYOUT tokens for media queries

use LAYOUT tokens for media queries

---

website/dynamic-blocks/do-and-avoid.js
website/dynamic-blocks/index.js

Also removes an old dynamic block

Better alignment of do don't image

---

website/dynamic-blocks/code-example.js
website/dynamic-blocks/do-and-avoid.js
website/dynamic-blocks/image.js
website/dynamic-blocks/index.js
website/dynamic-blocks/screen-reader-demo.js
website/dynamic-blocks/vision-filters.js
website/schema/component.js
website/src/components/a11y-filter.js

- Add image block
- Add image filter block
- Add screen reader text block

Add new dynamic blocks

---

website/src/components/brand-picker/brand-picker.js
website/src/pages/_app.js

Fix a redirect error on the brand picker and improve UI

Fix brand picker

---

website/admin/pages/settings.js
website/src/components/layout/navigation/navigation.js
website/src/pages/components/[component].js

Changes the url for components from an "_" to a "-".
Please test this including the navigation items.

Change urls

---

website/src/pages/components/[component].js

If you hide a tab in admin it is not shown.
If you hide all tabs other than design (which you can't hide), no tabs are shown.

conditional tabs

---

website/field-content/src/views/Field.js
website/field-content/src/views/editor/add-block.js
website/field-content/src/views/editor/block-disclosure-menu.js
website/field-content/src/views/editor/blocks/image-container.js
website/field-content/src/views/editor/dialog.js
website/field-content/src/views/editor/hooks/index.js
website/field-content/src/views/editor/index.js
website/field-content/src/views/editor/marks.js
website/field-content/src/views/editor/toolbar-components.js
website/field-content/src/views/editor/toolbar-icons.js
website/field-content/src/views/editor/toolbar.js
website/utils/dynamic-components-view.js

- generic dropdown menu component
- introduce formatting menu for less frequent marks
- add code mark

Block Editor: code mark

---

website/field-content/src/views/editor/block-disclosure-menu.js
website/field-content/src/views/editor/headings.js
website/field-content/src/views/editor/marks.js

- support active state on menu items
- support hot keys for each heading level
- style the items within the menu to be indicative of heading level

Block Editor: complete heading implementation

---

website/dynamic-blocks/README.md
website/field-content/package.json
website/utils/dynamic-components-view.js
yarn.lock

Adds documentation around dynamic blocks as well as the ability to archive blocks (remove from UI)

Document dynamic blocks

---

components/progress-rope/src/overrides/groupButton.js
components/progress-rope/src/overrides/list.js
components/progress-rope/src/overrides/stepButton.js

Line going to dotted
Line going from border colour to borderDark

Update ProgressRope styling

---

website/src/components/brand-switcher/brand-switcher.js
website/src/components/pages/single-component/blocks-hub.js
website/src/shortcodes.js

Add shortcodes:
Configure here:

Add shortcodes

---

website/dynamic-blocks/code-example.js
website/dynamic-blocks/headings.js

Updating default options for headings and code blocks to make adding content easier for @KateMacdonald  :smile:

Update heading and code dynamic block defaults

---

nginx/dev.conf
nginx/live.conf
nginx/staging.conf

* Fix for [Run the website in a sub dir](https://www.notion.so/thinkmill/Run-the-website-in-a-sub-dir-0a083dc7222a443aad450d90b7ad6f5f)
* Workaround for [Admin UI bundles returned with incorrect mime type](https://www.notion.so/thinkmill/Admin-UI-bundles-returned-with-incorrect-mime-type-66ec6663208042c8a77f1e3199b0a132)
* Added config for dev nginx environment
* Prep'ing for live deploy
* Some general tidying up of nginx conf

Merging recent devops changes back in to develop branch

---

website/dynamic-blocks/headings.js

wrap with conditional

---

website/dynamic-blocks/intro-section.js
website/dynamic-blocks/separator.js
website/dynamic-blocks/vision-filters.js
website/src/components/_utils.js
website/src/components/pages/single-component/code-tab.js
website/src/pages/design-system/[...page].js

- Intro section 
- Separator line
- background fix
- code tab content alignment
- Visual filter text/link ui fix

Ui updates

---

.gitignore
website/src/components/pages/single-component/blocks-hub.js

Also added prop-types.json to gitignore. Not sure if it's the same as GEL.json though. @dominikwilkowski

fix indent on lists

---

website/src/pages/design-system/[...page].js

fix zindex issue on sticky tab header

---

website/src/components/_utils.js

Another quick fix off the back of the meeting yesterday.

fix related content block on mobile

---

components/form-check/src/overrides/formCheck.js
components/form-check/src/overrides/option.js

I don't know if there was feedback from Intopia but the form-check strikes me as a list of things???

convert to semnatic html

---

website/dynamic-blocks/intro-section.js
website/src/components/_utils.js

fix jason parse bug

---

README.md
package.json
website/README.md
website/example.env
website/migrations/20200325005855_initial-users.js

Adding docs for the Keystone-powered GEL3 website, including:
* How to setup development environments
* How to create and apply migrations
* A overview of the production environments
* The deploy process

Website dev setup and deployment docs

---

components/modal/src/overrides/title.js
components/panel/src/overrides/heading.js
components/popover/src/overrides/heading.js
components/progress-rope/src/overrides/stepButton.js

We should always use the tokens over hard coded values.
That way if you ever introduce a font for the body you will be able to art-direct what weights we use where.

used font weights tokens over hardcoded ones

---

components/input-group/demos/design/input-group.js
components/input-group/examples/00-example.js
components/input-group/examples/10-type.js
components/input-group/examples/20-sizes.js
components/input-group/examples/30-states.js
components/input-group/examples/40-overrides.js
components/input-group/src/After.js
components/input-group/src/Before.js
components/input-group/src/Button.js
components/input-group/src/InputGroup.js
components/input-group/src/SelectField.js
components/input-group/src/Text.js
components/input-group/src/TextInputField.js
components/input-group/src/index.js
components/input-group/src/overrides/button.js
components/input-group/src/overrides/select.js
components/input-group/src/overrides/text.js
components/input-group/src/overrides/textInput.js

- Rename `type` prop... now `inputType` (was stopping us from being able to set `<button type="submit" />`)
- Rename `<Left />` and `<Right />` subcomponents... now `<Before />` and `<After />` (more consistent with button icon positioning options)
- Fix examples

Refactor input-group

---

.changeset/nervous-nails-tell.md
components/grid/examples/70-container.js
components/grid/src/Container.js
components/grid/src/Grid.js
components/grid/src/overrides/container.js
helpers/example/components/HomeDocs.js
helpers/example/components/HomeStart.js
helpers/example/components/Page.js
website/admin/pages/dashboard.js
website/admin/pages/settings.js
website/dynamic-blocks/code-example.js
website/dynamic-blocks/color-swatch.js
website/dynamic-blocks/do-and-avoid.js
website/dynamic-blocks/headings.js
website/dynamic-blocks/icons.js
website/dynamic-blocks/image.js
website/dynamic-blocks/intro-section.js
website/dynamic-blocks/props-table.js
website/dynamic-blocks/screen-reader-demo.js
website/dynamic-blocks/symbols.js
website/dynamic-blocks/vision-filters.js
website/src/components/_utils.js
website/src/components/brand-picker/brand-picker.js
website/src/components/header/home-page-header.js
website/src/components/pages/single-component/blocks-hub.js
website/src/pages/design-system/[...page].js
website/src/pages/design-system/index.js

Update Container styling to match GUI2 grid module, and provide new xsl breakpoint styling
Use px values too, we don't want the grid resizing when browser text size is changed

Further Grid refactor

---

components/grid/src/overrides/grid.js

Refactor grid gap

---

.changeset/tasty-days-beg.md
components/form-check/blender/recipe.js
components/form-check/package.json
components/form-check/src/overrides/formCheck.js
components/form-check/src/overrides/label.js
components/form-check/src/overrides/option.js

The blender HTML comes out as:
```
<div class="GEL-formCheck-v1_0_1">
<div class="GEL-formCheck-v1_0_1-option-size_medium">
<input type="checkbox" id="GEL-option-106" value="1" name="name1" class="GEL-Option-v1_0_1" />
<label for="GEL-option-106" class="GEL-formCheck-v1_0_1-label-size_medium-type_checkbox">
Your option 1
</label>
</div>
<div class="GEL-formCheck-v1_0_1-option-size_medium">
<input type="checkbox" id="GEL-option-107" value="2" name="name1" class="GEL-Option-v1_0_1" />
<label for="GEL-option-107" class="GEL-formCheck-v1_0_1-label-size_medium-type_checkbox">
Your option 2
</label>
</div>
<div class="GEL-formCheck-v1_0_1-option-size_medium">
<input type="checkbox" id="GEL-option-108" value="3" name="name1" class="GEL-Option-v1_0_1" />
<label for="GEL-option-108" …
```

formcheck blender support

---

.changeset/wise-balloons-cheer.md
components/list/blender/recipe.js
components/list/package.json
components/list/src/Item.js
components/list/src/overrides/icon.js
components/list/src/overrides/item.js
components/list/src/overrides/list.js

Note: Marked WIP as we will need to review the approach here. 
The following HTML is currently required to implement a basic nested list 😳...
```
<ul role="list" class="GEL-body-v1_0_0-beta_2-list-type_bullet">
<li class="GEL-list-v1_0_0-beta_2-item-look_primary-nested_0-spacing_medium-type_bullet">
List item text
</li>
<li class="GEL-list-v1_0_0-beta_2-item-look_primary-nested_0-spacing_medium-type_bullet">
List item text
<ul role="list" class="GEL-body-v1_0_0-beta_2-list-type_bullet">
<li class="GEL-list-v1_0_0-beta_2-item-look_primary-nested_1-spacing_medium-type_bullet">
List item text
</li>
<li class="GEL-list-v1_0_0-beta_2-item-look_primary-nested_1-spacing_medium-type_bullet">
List item text
</li>
<li class="GEL-list-v1_0_0-beta_2-item-look_primary-nested_1-spacing_medium-type_bulle …
```

List blender support

---

.changeset/strong-lions-press.md
.changeset/thick-shoes-pay.md
components/list/examples/00-look.js
components/list/examples/30-icon.js
components/list/src/Item.js
components/list/src/List.js
components/list/src/overrides/icon.js

Also changes the default look to `hero` (for bullets only)

List: Remove jump link auto-focus

---

.changeset/perfect-laws-brush.md
.changeset/shy-worms-flow.md
components/a11y/examples/10-SkipLink.js
components/a11y/src/overrides/skipLink.js
components/a11y/src/overrides/visuallyHidden.js
components/list/src/overrides/list.js

- Fix Tick list assistive text
- Make a11y component styling more better

Fix List, SkipLink and VisuallyHidden components

---

website/dynamic-blocks/separator.js
website/package.json
website/src/components/header/component-page-header-image.js
website/src/components/header/home-page-header.js
website/src/components/header/page-header.js
website/src/components/layout/footer.js
website/src/components/layout/layout.js
website/src/components/separator/separator.js
website/src/components/symbols/WbcBackgroundLeftSvg.js
website/src/pages/design-system/[...page].js
website/src/pages/design-system/index.js

- Footer styling
- Space for footer
- Footer animation
- Document structure
- Throttle rather than debounce
- Fix WBC svg height warning

Update page shell

---

website/dynamic-blocks/intro-section.js

Jumplink icon and text styling, doc structure, use Body, remove hr's

Update component page

---

website/src/components/brand-switcher/brand-switcher.js
website/src/components/layout/navigation/BackToGelSvg.js
website/src/components/layout/navigation/navigation-group.js
website/src/components/layout/navigation/navigation-item.js
website/src/components/layout/navigation/navigation.js
website/src/components/layout/sidebar.js

- fix sidebar off-canvas transition on page load
- slightly better a11y support: focus styling etc
- active page nav item styling

Navigation fixes

---

website/dynamic-blocks/intro-section.js
website/dynamic-blocks/separator.js
website/src/components/brand-switcher/brand-switcher.js
website/src/components/header/home-page-header.js
website/src/components/header/page-header.js
website/src/components/layout/footer.js
website/src/components/layout/layout.js
website/src/components/layout/navigation/navigation.js
website/src/components/layout/sidebar.js
website/src/components/separator/separator.js
website/src/pages/design-system/[...page].js

- Fix safari sticky bug (use default window scrolling, rather than element overflow scrolling)
- Better shadow styling
- Restyle sidebar positioning

Fix page shell

---

website/dynamic-blocks/intro-section.js
website/src/components/brand-switcher/brand-switcher.js
website/src/components/layout/section.js
website/src/pages/design-system/index.js

Remove react-select, roll our own using the ButtonDropdown component
Also some updates to Section component (used by Homepage and now Intro section)

Update brand switcher

---

.changeset/twelve-ghosts-scream.md
components/button/src/Button.js
components/grid/src/Cell.js
components/grid/src/Container.js
components/grid/src/Grid.js
components/grid/src/overrides/cell.js
components/grid/src/overrides/container.js
components/grid/src/overrides/grid.js

Gives Container, Grid and Cell an optional tag prop

Grid tag prop

---

website/src/components/_utils.js
website/src/components/pages/single-component/blocks-hub.js

- hundefined bug
- size bug
- key bug

Fix blocks hub

---

website/src/components/brand-switcher/brand-switcher.js

Individually optimises brand switcher logo sizing/alignment (since we're not using small multibrand logos)

Optimise website brand switcher logos

---

.changeset/real-monkeys-brush.md
components/form-check/package.json
components/form-check/src/overrides/label.js

use Body component for label text

FormCheck 

---

website/dynamic-blocks/code-example.js
website/dynamic-blocks/color-swatch.js
website/dynamic-blocks/do-and-avoid.js
website/dynamic-blocks/headings.js
website/dynamic-blocks/image.js
website/dynamic-blocks/screen-reader-demo.js
website/dynamic-blocks/vision-filters.js
website/src/components/pages/single-component/blocks-hub.js
website/src/components/related-information/related-information.js
website/src/components/section/section-heading.js

- adjust layout
- remove column offsets 
- adjust span widths

Adjust website layout (first pass)

---

.changeset/great-hotels-deny.md
.changeset/mean-chicken-turn.md
components/button/examples/00-look.js
components/button/examples/10-button-tags.js
components/button/examples/20-sizes.js
components/button/examples/60-icons.js
components/button/src/Button.js
components/button/src/overrides/button.js

Note: branched from https://github.com/WestpacGEL/GEL/tree/feature/button-link

Unstyled button 

---

.changeset/great-hotels-deny.md
components/button/examples/00-look.js
components/button/examples/10-button-tags.js
components/button/examples/60-icons.js
components/button/src/overrides/button.js

TODO: Need to check link look buttons (now with horizontal padding) used in the following....
- Alert close button (X)
- Modal close button (X)
- Popover close button (X)
- usePagination example
- Website brand switcher
- Website page header
- Website footer 'Top' button

WIP: Revert link look button padding trim

---

helpers/example/components/SidebarDocs.js
helpers/example/components/SidebarStart.js

Replaces the horizontal button UI with a more scalable Select based control

New testing brand selector UI

---

.changeset/plenty-dolphins-knock.md
components/pagination/src/overrides/list.js

Add list role to enhance UX in VoiceOver
Now consistent with other lists... breadcrumb, progress-rope etc

Fix pagination list role

---

.changeset/olive-guests-watch.md
components/pagination/src/overrides/link.js

Fix pagination disabled

---

website/README.md

…and made the process a bit more transparent

Added documentation for moving data from staging to live and reverse

---

components/alert/blender/script.js
components/button-dropdown/blender/script.js
components/modal/blender/script.js
components/popover/blender/script.js
components/progress-rope/blender/script.js

Updates to existing components with blender script functionality. Now consistent with new Tabcordion JS pattern.

New blender JS public API pattern rollout

---

components/pictogram/blender/recipe.js
components/pictogram/examples/00-default.js
components/pictogram/examples/10-modes.js
website/dynamic-blocks/pictograms.js

Updates blender recipe and test examples with dynamic brand code filtering
Adds RAMS brand filter to website block

Pictogram list filtering improvements

---

website/src/pages/design-system/downloads/index.js

fixes https://trello.com/c/vypyWSxi/277-dom-downloads-page-re-instate-correct-documentation-link
fixes https://trello.com/c/5UEjIRXw/413-dom-add-dummy-core-selection-in-downloads-page

added documentation links back and pinned core to the top of our download list

---

website/src/pages/design-system/[...page].js

fixed https://trello.com/c/xSpmXsHZ/270-dom-website-is-it-possible-to-make-the-page-scroll-up-when-a-new-tab-is-selected

fixing scroll to top on tab change

---

.changeset/sour-bulldogs-mate.md
components/button/src/overrides/button.js

Removes border styling from link look buttons

Simplify link button border styling

---

website/src/components/header/page-header.js
website/src/pages/design-system/[...page].js
website/src/pages/design-system/downloads/index.js

Fixes page header scroll shadow missing on component and download pages
also fixes downloads page blender options list styling

Fix website page header

---

components/selector/examples/10-option-hint.js
components/selector/examples/40-secondary-label.js
components/selector/package.json
components/selector/src/Option.js
components/selector/src/overrides/hint.js
components/selector/src/overrides/icon.js
components/selector/src/overrides/labelPrimary.js
components/selector/src/overrides/labelSecondary.js
components/selector/src/overrides/pictogram.js
components/selector/src/overrides/text.js

Also added a few examples for bank account numbers as hints

Selector: Add secondary label ellipsis truncation

---

.changeset/curvy-tomatoes-brush.md
components/button-group/src/ButtonGroupItem.js
components/selector/src/Option.js
components/switch/demos/design/switch.js
components/switch/src/Switch.js
components/text-input/src/overrides/select.js
components/text-input/src/overrides/textInput.js
components/text-input/src/overrides/textarea.js

This gives devs the ability to set focus for our input components programmatically

Input components: forwardRef to input node

---

.changeset/three-onions-lie.md
components/core/examples/70-useFonts.js
components/core/src/useFonts.js

Looking into #772 this could be a neat solution

added a way for someone to override anything inside the useFont hook

---

.changeset/poor-dragons-sparkle.md
components/list/package.json
components/list/src/overrides/list.js

Simplifies the tick/cross assistive text approach, approved by Intopia

List: Tick list a11y

---

package.json
yarn.lock

Updates webpack-dev-server to stable 4.0.0 release.

Update webpack-dev-server to 4.0.0

---

.changeset/old-eels-teach.md
components/form/demos/design/name-full.js
components/form/demos/design/name-simple.js
components/form/demos/design/name.js
components/form/demos/design/names-given.js
components/form/demos/design/phone-simple.js
components/link/src/overrides/icon.js
components/list/CHANGELOG.md
components/list/examples/00-type.js
components/list/src/Item.js
components/list/src/List.js
components/list/src/overrides/content.js
components/list/src/overrides/item.js
components/list/src/overrides/list.js

Just waiting to hear back from the others about text alignment in the situation below...

a11y updates

---

components/tabcordion/package.json

Add missing react-dom peerDependency in @westpac/tabcordion

---

website-backend/admin/component-blocks/article.tsx
website/src/components/article/renderers/ArticleCard.js

Two changes included in this PR —
1. Article card image should be used instead of page image in articles home and Admin UI editor
2. Article title should not be shown in place of article description in articles home

Article title and card image changes

---

components/core/package.json
yarn.lock

Updated a package that was missed during the upgrade to React 18.2.0

Updated "react-is" package to version "18.2.0".

---

brands/BSA/src/index.d.ts
brands/BTFG/src/index.d.ts
brands/RAMS/src/index.d.ts
brands/STG/src/index.d.ts
brands/WBC/src/index.d.ts
brands/WBG/src/index.d.ts
components/core/src/blenderUtils.ts

fix(brand): brand types sting to string

---

components/a11y/tests/unit/accessibility-helpers.spec.js
components/collapsible/tests/unit/collapsible.spec.js
components/compacta/tests/unit/compacta.spec.js
components/date-picker/tests/unit/date-picker.spec.js
components/footer/tests/unit/footer.spec.js
components/fork/src/Fork.tsx
components/fork/tests/unit/fork.spec.js
components/form-check/tests/unit/form-check.spec.js
components/form/tests/unit/form.spec.js
components/grid/src/Cell.tsx
components/grid/src/Grid.tsx
components/grid/tests/unit/grid.spec.js
components/input-group/src/TextInputField.tsx
components/input-group/tests/unit/input-group.spec.js
components/list-group/tests/unit/list-group.spec.js
components/modal/tests/unit/modal.spec.js
components/pagination/tests/unit/pagination.spec.js
components/popover/src/Popover.tsx
components/popover/tests/unit/popover.spec.js
components/progress-bar/tests/unit/progress-bar.spec.js
components/progress-rope/src/Step.tsx
components/progress-rope/tests/unit/progressRope.spec.js
components/repeater/tests/unit/repeater.spec.js
components/selector/tests/unit/selector.spec.js
components/sidebar/tests/unit/sidebar.spec.js
components/switch/tests/unit/switch.spec.js
components/text-input/tests/unit/text-input.spec.js

- Adding the simple render test for each component.

fix(tests-render): creating basic test for every component

---

components/input-group/src/InputGroup.tsx
components/input-group/src/TextInputField.tsx
components/input-group/src/overrides/inputGroup.js
components/input-group/src/overrides/textInput.js

- fowardRef on InputGroup in order to use register method of react-hook-forms.

feat(input-group): forwardRef input-group

---

components/input-group/tests/unit/input-group.spec.js

-added unit tests for Input Group, all tests are working as intended

WLT-21646 Input Group Tests

---

brands/WBC/src/types.d.ts
components/form/tests/unit/field.spec.js
components/form/tests/unit/fieldset.spec.js
components/form/tests/unit/form.spec.js
components/form/tests/unit/formGroup.spec.js
components/input-group/tests/unit/input-group.spec.js
components/label/tests/unit/label.spec.tsx
components/label/tsconfig.json
helpers/tests/nesting-test.js
helpers/tests/overrides-test.js

- added TS tests for label
- added new tests for previous components I worked on to increase coverage
- minor change to nesting-test and overrides-test to export to avoid TS issues
- minor changes to WBC types to add key to colors to avoid TS issues in test

Label Unit Tests

---

components/icon/examples/50-all-icons.js
components/pictogram/examples/00-default.js
components/symbol/examples/20-all-symbols.js
components/symbol/examples/30-all-logos.js

Reverts WestpacGEL/GEL#996
Reverting due to the build error

Revert "Fixes to Icon, Pictogram and Symbol example pages"

---

components/icon/examples/50-all-icons.js
components/pictogram/examples/00-default.js
components/symbol/examples/20-all-symbols.js
components/symbol/examples/30-all-logos.js

Revert "Revert "Fixes to Icon, Pictogram and Symbol example pages""

---

components/flexi-cell/examples/01-account-list.tsx
components/flexi-cell/examples/02-payee-list.tsx
components/flexi-cell/examples/03-country-list.tsx
components/flexi-cell/examples/04-foreign-currency-list.tsx
components/flexi-cell/examples/05-promo-tiles-horizontal-list.tsx
components/flexi-cell/examples/06-promo-tiles-vertical-list.tsx
components/flexi-cell/examples/07-product-tiles-list.tsx

copying demos to examples folder

Feature/WLT-28582: create flexi cell
