WestpacGEL/GEL

components/core/src/Theme.js

We shouldn't be removing the default focus styling until we implement it.

fix(theme): remove focus outline none

---

components/core/src/Core.js
helpers/example/index.js

Reverts the document back to a 16px font-size default
1rem = 16px
Also changes `isChecked` props to `checked` so they're inline with where we're going with boolean prop naming throughout.
The 'focusable elements' example is broken. Fixed with updates to Button, yet to merge (WIP).

Remove document 10px fontSize reset

---

components/icon/src/Icon.js

This is a convenience PR, since a lot of components depend on the `Icon` component to work - so we don't need to make a temporary fix in each branch to be able to preview it.
I say `temporary` because I believe the Icon component is under work in #136

Making the Icon component work with useTheme and useMediaQuery

---

components/tabcordion/examples/10-mode.js
components/tabcordion/examples/20-look.js
components/tabcordion/examples/40-configurable.js
components/tabcordion/examples/50-local-tokens.js
components/tabcordion/src/Tab.js
components/tabcordion/src/Tabcordion.js

• chore(tabcordion): remove unnecessary named destructured vars, tidy up
• fix(tabcordion): fix lego accordion borderLeftColor
• chore(tabcordion): rename appearance example (now look), update examples to use responsive mode explicitly
• fix(tabcordion): fix incorrect justify prop name in configurable example
• fix(tabcordion): fix forwardRef and instanceIdPrefix prop issue in local tokens example

Fix Tabcordion

---

babel.config.js
website/src/pages/_app.js

Previously an incorrect querystring for the brand would cause an infinite loop.
Now it will redirect to brand selection page or get the brand from the cookie.

Fix brand query string redirect bug

---

website/dynamic-blocks/props-table.js

`SPACING` actually has an argument that removes the unit, silly Dom

fixed spacing and parseInt 

---

website/src/components/brand-switcher/brand-switcher.js

Blocks build on case-sensitive file systems

Correcting casing for ref to package `@westpac/icon`

---

components/form/src/ErrorMessage.js

Using `<>` causes our pragma to freak out.

fixed fragment use in component

---

website/field-content/src/views/editor/add-block.js
website/field-content/src/views/editor/block-disclosure-menu.js
website/field-content/src/views/editor/blocks/link.js
website/field-content/src/views/editor/blocks/paragraph.js
website/field-content/src/views/editor/dialog.js
website/field-content/src/views/editor/hooks/useClickOutside.js
website/field-content/src/views/editor/hooks/useKeyPress.js
website/field-content/src/views/editor/index.js
website/field-content/src/views/editor/toolbar-components.js
website/field-content/src/views/editor/toolbar-icons.js
website/field-content/src/views/editor/toolbar.js
website/index.js
website/schema/component.js
website/utils/dynamic-components-view.js

The original PR (#274) was closed pre-emptively. This wraps up a lot of the work from there.
- fix selection behaviour between blocks
- move insert menu to the toolbar
- only display the disclosure line for "dynamic-component" blocks
- highlight blocks that were left in "edit-mode"
- provide placeholder text to improve affordance
- disable "marks" for dynamic-components
- only show the insert menu when the appropriate blocks are available

Block editor UI polish

---

website/src/components/pages/single-component/blocks-hub.js

The fix is just to pass node data to the serialized heading

Fix: Heading Data

---

website/dynamic-blocks/icons.js

Quick fix, span text is more condensed than <code />

fix icon label overflow bug

---

pm2-post-deploy.sh

Adding the `--frozen-lockfile` option when deploying. This prevents "optimisations" of the lock file that break future deploys. 
See yarn issue [#4379: yarn install changes yarn.lock file](https://github.com/yarnpkg/yarn/issues/4379).

Deployment tweak; should prevent `yarn.lock` being modified on deploy

---

website/dynamic-blocks/color-swatch.js
website/src/secondary-colors.js

I was unable to test this locally as Keystone is broken... but theoretically this should now also show the print colors for the `Secondary Palette`.

added print colors to the swatches

---

website/src/components/pages/single-component/blocks-hub.js
website/src/pages/design-system/[...page].js

Adds shortcodes to dynamic blocks. 
How it works: 
It looks at all the props for dynamic blocks and if they are a string it attempts to replace the text with shortcodes before passing to the component.
Not that this effects all string props E.g, the heading tag prop `h2` is a sting. This will never be altered because it's not going to match the shortcode syntax: `[[(.*)]]`. I think this should always be safe but I don't love it.
Caveat #2 this will not work for nested props, say we have a dynamic component with a list of paragraphs in a single prop: 
```
<DyamicComp paragraphs={['para1', 'para 2']} /> 
```
Or complex data in a single prop:
```
<DyamicComp data={{
heading: 'Why is this not flat?'
paragraph: "I should be a separate prop"
}} /> 
```
Neither of the above examples will have …

Add shortcodes to all the things

---

website/dynamic-blocks/intro-section.js
website/dynamic-blocks/props-table.js
website/dynamic-blocks/screen-reader-demo.js
website/dynamic-blocks/vision-filters.js
website/src/components/_utils.js
website/src/components/pages/single-component/blocks-hub.js
website/src/components/pages/single-component/design-tab.js
website/src/pages/design-system/[...page].js

- Requested UI changes to the related content
- Change textOnlySlateRenderer to only use "enter" key for any spacing as per request. No additional margin is required for text outside the blocks.
- Changes to Screen reader UI and addition of editor option to add to TOC
- Props table option to add to TOC
- Related content logic to add to TOC (only if on design tab)

toc links and related info ui

---

website/dynamic-blocks/heading.js
website/dynamic-blocks/headings.js
website/dynamic-blocks/image.js
website/dynamic-blocks/intro-section.js
website/dynamic-blocks/props-table.js
website/dynamic-blocks/screen-reader-demo.js
website/dynamic-blocks/separator.js
website/src/components/_utils.js
website/src/components/pages/single-component/blocks-hub.js

- adds margins to the container that wraps all blocks
- removes global margin
- text is exception to the extra margins
- removes unnecessary !importants
- moves a couple of components back into the main export as they are short and extracting them doesn't improve legibility.

Make spacing more consistent across blocks

---

website/index.js

As per the [quite significant deep dive](https://gist.github.com/molomby/6fa22c165e0025f0f83d55195f3c6e37) we did, this is required for secure cookies to work when running behind a reverse proxy (most of the time).

Apply the secure cookie workaround

---

website/example.env
website/index.js

This needs to be set to make the app production ready.
I've added config to the live and staging servers setting this value so all we need to do is roll this change out. All sessions will be reset (once) when this change is deployed (but after that will be stable).
Developers will need to add a `COOKIE_SECRET` value to their `.env` files, as per the notes in `website/example.env`.

Adding cookie secret config to Keystone init

---

components/core/src/GEL.js
components/grid/src/Cell.js
components/grid/src/Grid.js
components/grid/src/overrides/grid.js

- Updates Grid's `rowGap` propType declaration (should be able to take string value - rowGap's default CSS value is 'normal')
- Updates Cell's `left` propType declaration (should be able to take string value – grid-column-start's default value is 'auto')
Also includes a fix for GEL `brand` prop's incorrect propType declaration

Refactor grid

---

.changeset/short-elephants-wash.md
components/icon/examples/60-overrides.js
components/icon/src/Icon.js

The icon omited the `icon` name in it's state. Must have been deleted when we moved to nested `state` prop.
I also showed how one may override the entire icon paths if they chose to.

fixed icon state and showed how to override an icon entirely

---

.changeset/friendly-clouds-complain.md
.changeset/short-elephants-wash.md
.changeset/smart-dragons-rescue.md
.changeset/strange-ads-reply.md
components/core/demos/design/body-fonts.js
components/core/demos/design/brand-font.js
website/dynamic-blocks/intro-section.js
website/src/components/_utils.js
website/src/components/header/home-page-header.js
website/src/components/header/page-header.js
website/src/secondary-colors.js

Updates to the website
- remove custom color mappings etc
- update fonts demos (in `@westpac/core`) - now renders demos for all weights
Hey @jaortiz ... we have relative links to the website in our published packages (demos)
e.g. `import { Playground } from '../../../../website/src/components/playground/macro';`.
Is that kosher?

Brand updates

---

website/dynamic-blocks/color-swatch.js
website/dynamic-blocks/headings.js
website/dynamic-blocks/intro-section.js
website/dynamic-blocks/vision-filters.js
website/field-content/src/views/editor/blocks/blockquote.js
website/src/brand-overrides.js
website/src/components/body/body.js
website/src/components/body/index.js
website/src/components/brand-picker/brand-picker.js
website/src/components/header/home-page-header.js
website/src/components/list/index.js
website/src/components/list/item.js
website/src/components/list/list.js
website/src/components/pages/single-component/blocks-hub.js
website/src/pages/design-system/downloads/index.js
website/src/pages/design-system/index.js

Remove the brand overrides and instead create our own website specific `<Body />` and `<List />` components, which wrap and override the standard GEL Body and List components. 
This approach will mean we won't have issues rending our GEL components in the example Wells for example. 
Basically where our GEL Website component styling veers off standard GEL component styling (e.g. larger Body line-height and font-size), using this approach will mean any components we do want to look like standard wont need overriding back to standard. We only override the parts of the site we need to, not everything site wide.

Fix website components

---

website/src/components/playground/index.js

We were using our `<Well />` component to render the example blocks, but since `<Well />` renders as a `<Body />`, and `<Body />` styles links etc, examples such as `<Breadcrumb />` were being affected by Body styles.
It's best show our examples accurately in their native environment, not affected by being rendered inside other component(s).

Fix website example block

---

.changeset/ninety-owls-cry.md
components/heading/src/BrandHeading.js
components/heading/src/overrides/brandHeading.js
website/src/brand-overrides.js
website/src/components/header/home-page-header.js
website/src/components/header/page-header.js

New `uppercase` prop that puts the BrandHeading in `text-transform: uppercase` and `line-height: 1` as required by our brands

BrandHeading uppercase option

---

components/button-dropdown/blender/script.js
components/popover/blender/script.js

event.keyCode is being deprecated https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/keyCode

Fix keyCode

---

website/src/pages/design-system/[...page].js

Strips tabcordion PanelBody styling, removes use of <Body /> component and overrides tabButton styling
Fixes:
- broken breadcrumb styling in example box
- incorrect page padding
- tabButton hover styling

Fix website body styling

---

components/button-group/src/ButtonGroup.js
components/button-group/src/overrides/button.js

This was never intended to be an option. It was never communicated. 
Issue: It's not clear enough when a button is selected, and is not accessible.

Remove button-group faint look option

---

.changeset/fresh-cooks-punch.md
brands/BOM/tokens/type.js
brands/BSA/tokens/type.js
brands/BTFG/tokens/type.js
brands/RAMS/tokens/type.js
brands/STG/tokens/type.js
brands/WBC/tokens/type.js
brands/WBG/tokens/type.js

Rolled back to GEL2 system stack
Propose we consider simplifying (as github did in 2018). `Roboto, Oxygen, Ubuntu, Cantarell, Fira Sans, Droid Sans` no longer specified, and emoji specific fonts listed too. We should probs do this.
https://markdotto.com/2018/02/07/github-system-fonts/#the-stack

Update system font stack

---

components/selector/examples/00-examples.js
components/selector/examples/10-option-hint.js
components/selector/examples/20-pictogram.js
components/selector/examples/30-icon.js
components/selector/examples/40-secondary-label.js
components/selector/examples/50-disabled-state.js
components/selector/src/Option.js
components/selector/src/Selector.js
components/selector/src/overrides/indicator.js
components/selector/src/overrides/label.js
components/selector/src/overrides/optionBtn.js
components/selector/src/overrides/selector.js

Previous attempt didn't work for keyboard users; who select the first option on arrival, and only fire onChange on spacebar press or first arrow down (so wouldn't be able to actually choose anything other than the first or second option, before being taken to the next step/page in the form) 😬
New approach has been implemented as `type="button"` rather than a styling prop (`nextIndicator`). It uses buttons with `aria-pressed` attributes to indicate (a11y) state change. Rather than a separate input for each option, there is one hidden input with dynamic value. 
The button elements have a `data-value` attribute for use in the blender. Some jQuery will take the currently selected button onClick, and set the hidden input value to the button's data-value.

Selector: tweak type with next indicator

---

helpers/ds-info.js

When you switch branches (e.g. from branch introducing header and footer back to develop), Git may not remove directories that were created on the branch you're leaving. This crashes GELjson command as it only looks for directories in `components` directory, and assumes `package.json` will be there. Consequently, with empty folders present in `components` directory you're unable to install GEL repository.

Fix crash on GELjson command if empty directories are present in `components` directory

---

components/tabcordion/package.json
components/tabcordion/src/overrides/panelBody.js
yarn.lock

Fixes #792
Components other than Tabcordion, as well as secondary dependencies of GEL, use `resize-observer-polyfill`. Tabcordion uses `@juggle/resize-observer`. Consequently, installing GEL resulted in two polyfills for the same feature included in the bundle.

Fix duplicated ResizeObserver polyfills

---

package.json
yarn.lock

Current bug in Prisma 3.10.0 means that presently accessing any list with a foreign key will crash the instance. 
Pinning to 3.7.0 in our resolution should negate this until the issue is resolved on prisma's end.

pin prisma version to 3.7.0, avoids existing prisma bug in 3.10.0

---

website-backend/keystone.ts
website/src/pages/articles/[slug].js
website/src/pages/articles/index.js

Current build process does not support fetching API data during the build since frontend and API builds are not sequential. This pull request switches the approach from statically building article pages to server rendering the pages where we fetch article home and article page data during server rendering.

Server render article pages instead

---

nginx/gel3-keystone-routes.conf

Default nginx file upload limit is 1Mb. Some of the image files being uploaded for article pages are >1MB in size and we need to support that.
Changes:
- Increase nginx file upload size limit

Increase nginx file upload size limit

---

components/autocomplete/examples/00-default.js
components/autocomplete/tests/integration/autocomplete.cypress.js
components/autocomplete/tests/pages/default.page.ts

Removed direct test of red border color around the Autocomplete component when invalid prop is applied and replaced with comparison between the css borderColor styles of the Autocomplete when it's invalid and when it's in "normal valid" state respectively.

Hotfix/no ref/unit tests autocomplete

---

components/icon/examples/50-all-icons.js
components/pictogram/examples/00-default.js
components/symbol/examples/20-all-symbols.js
components/symbol/examples/30-all-logos.js

-fixed issue where defaultProps.assistiveText was causing errors on example pages for icon symbol and pictogram
- was recommended to just remove that entire line as it wasn't really necessary

Fixes to Icon, Pictogram and Symbol example pages
